### PR TITLE
add max, experimental, and current capacities to RenogyBatt

### PR DESCRIPTION
**Pull request by acmagn**
The current Renogy app reports on "Max Capacity" (potential full capacity) and current capacity. I added these to the RenogyBatt add-on, and also separated out the experimental capacity reading into "exp_capacity" for clarity.

### CODE REVIEW

**Comment by Anto79-ops** [comment]
Awesome and thanks! Look forward to @Olen to merge this!

**Comment by Olen** [comment]
> Awesome and thanks! Look forward to @Olen to merge this!

Have yo tested it?
I don't have a Renogy myself, but if it works, and don't break anything else, I'll happily merge.

**Comment by Anto79-ops** [comment]
> > Awesome and thanks! Look forward to @Olen to merge this!
> 
> Have yo tested it?
> I don't have a Renogy myself, but if it works, and don't break anything else, I'll happily merge.

I can test it today in the next hour. Can you please remind me which Depot do I clone?

**Comment by Olen** [comment]
> > > Awesome and thanks! Look forward to @Olen to merge this!
> > 
> > 
> > Have yo tested it?
> > I don't have a Renogy myself, but if it works, and don't break anything else, I'll happily merge.
> 
> I can test it today in the next hour. Can you please remind me which Depot do I clone?

If you have the "gh" binary, you can use `gh pr checkout 22` (inside your local repo)

Or you can do something like
`git fetch origin pull/22/head:renogy_max`

and then 

`git checkout renogy_max`

More info e.g. here:

https://stackoverflow.com/questions/15397059/how-do-i-get-a-specific-pull-request-on-my-machine#32447815

**Comment by Anto79-ops** [comment]
thanks at @Olen  ran your commands:

Renogy_battery

and I think it took.

I do see new entities here (in green dots)

renogy_entities

The red dot, is the old capacity number I think...I guess that can be removed once we confirm that the new capacity numbers are working.

Before I started the script I logged into the Renogy app and I can confirm the numbers are correct (match what the app reads) for Max capacity and capacity (which is essentially SOC). In my test case, I'm using a 100 ah battery so it could be easier in my case, if some with a 200 ah battery can also test, that would be good. So far soo good here @acmagn !! awesome work! thanks.

By the way, what is Exp (experimental?) capacity telling us?

**Comment by acmagn** [comment]
Thanks @Anto79-ops for testing it, I'm glad to see it's working on your end! The max_capacity reading was a bit of a shot-in-the-dark.
@Olen  I also tested it locally and I have a 200ah Renogy battery. I wish I could do a small test on a different type of battery though.

Anto79-ops -- Experimental capacity is my own calculation of the current capacity. For whatever reason, my batteries slowly get de-synced from reporting the correct capacity and my own calculations have been an incredibly useful second opinion of what state they are actually in. The initial experimental reading is wrong, but after a few days of running the monitor it usually gets to be pretty accurate.

**Comment by Olen** [comment]
I'll just merge it. Hopefully you will be able to fix it if any bugs are discovered

**Comment by Anto79-ops** [comment]
Working well here since install. Thanks all!

**Comment by Anto79-ops** [comment]
Been running the merged code (latest code) for a couple of days now....no issues to report on my end. Thanks for adding this @acmagn and @Olen!

**Pull request merged**
